### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by lisalan520** [synthicity/synthpop#24]
Good morning,

2 URL issues in census_helpers.py:

1. self.base_url = "http://paris.urbansim.org/data/pums/" 
This URL is not working now. It worked weeks ago when I first try this tool.

2. self.fips_url = "https://www.census.gov/geo/reference/codes/files/" \
                        "national_county.txt"
This URL is currently "http://www2.census.gov/geo/docs/reference/codes/files/national_county.txt", and it doesn't have column names in the file.

Thanks!

**Comment by fscottfoti** [comment]
For the first one, our server crashed at the end of last week.  I will try and get this back up when I get the chance.

**Comment by lisalan520** [comment]
Thanks!

**Comment by lisalan520** [comment]
Hi @fscottfoti Did you get a chance to restore the pums URL yet?

**Comment by fscottfoti** [comment]
Not yet.  And I seem to have lost the code to do so.  Sigh, not sure how I managed to not get it checked in.  It wasn't a complicated script but it will take some remembering of where data came from etc.

**Comment by lisalan520** [comment]
Got it. Thanks!

**Comment by semcog** [comment]
Hi Fletcher

I just tested the code. By using these two URLs:
self.pums_relationship_file_url = "http://www2.census.gov/geo/docs/maps-data/data/rel/2010_Census_Tract_to_2010_PUMA.txt"
&
self.fips_url = "https://raw.githubusercontent.com/keithlayne/ansi_codes/master/data/national_county.txt"

I was able to get the Census starter to work. However, when running to 

%time households, persons, fit = synthesize_all(starter, indexes=[ind]) 

An errors showed up as:
error: [Errno 10054] An existing connection was forcibly closed by the remote host.

Any thoughts on the possible causes?
Thanks.

**Comment by fscottfoti** [comment]
I think it's still the same issue.  Our server crashed and so the built-in data is no longer working.  Unfortunately this was one of the nicest features of synthpop but you now have to bring your own data from PUMS and ACS...

**Comment by mckennasean** [comment]
Looks like the PUMS dataset still is not accessible on urbansim.org. Any ideas for a workaround besides manually assembling your own dataset?

**Comment by fscottfoti** [comment]
@janowicz haven't you made some progress with this recently?  Or will make some progress soon?

**Comment by janowicz** [comment]
Ah, yes-  some work on this was done.  I have to upload the files to the
new server, then update the branch with modified links.  I estimate that
I'll make a pull request by early next week!

**Comment by janowicz** [comment]
As of the most recent merge, the url's in the code should be working now.  Thanks!
